# Generated by Django 6.0.5 on 2026-05-10 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='track',
        ),
        migrations.AddField(
            model_name='trainee',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='personal_image',
            field=models.ImageField(blank=True, null=True, upload_to='trainees/images/'),
        ),
    ]
